# Generated by Django 3.0.7 on 2020-07-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='payment_type',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], default='Mpesa', max_length=120),
        ),
    ]
