# Generated by Django 3.0.7 on 2020-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_billingprofile_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], max_length=120, null=True),
        ),
    ]
