# Generated by Django 3.0.7 on 2020-07-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingprofile_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='payment_type',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], default='Mpesa', max_length=120),
        ),
    ]
