# Generated by Django 3.0.7 on 2020-07-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20200703_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='payment_type',
        ),
    ]
