# Generated by Django 3.0.7 on 2020-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200616_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], default='Mpesa', max_length=120),
        ),
    ]
