# Generated by Django 3.0.7 on 2020-07-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('cash', 'Cash')], max_length=120),
        ),
    ]
